import './style.css';
const worlds={morri:{label:'MORRI HUT',url:'https://madmorrigan.com/morri/',status:'MYSTERY ENGINE // ONLINE'},witch:{label:'WITCHDIX',url:'https://witchdix.com/',status:'GRIMOIRE // LISTENING'},xander:{label:'XANDER ZOMBIE',url:'https://xanderzombie.com/',status:'NARRATIVE ENGINE // UNDEAD'}};
const projects={terminal:['BRAIN CONNECT','AI orchestration / machines / experiments'],bench:['WORKBENCH','Raspberry Pi · hardware · network experiments'],bike:['WET BEARD','Quest engine escaped into the real world'],rack:['ÜBERCORP','Corporate systems with pirate interference'],drawer:['BORING HUMAN DOCUMENTS','Résumé · work history · responsible-adult evidence']};
document.querySelector('#app').innerHTML=`<main class="shop"><div class="room"><div class="pipes"></div><div class="crt" data-hot="terminal"><b>ARKMATX</b><span>WORKSHOP OS<br>WORLD BUS: ACTIVE<br>_</span></div><div class="bench" data-hot="bench"><i></i><i></i><i></i><strong>TOOLS / PI / BAD IDEAS</strong></div><div class="bike" data-hot="bike">◯━╋━◯</div><div class="rack" data-hot="rack"><em></em><em></em><em></em><small>UBER // RACK 03</small></div><div class="radio" id="radio"><span>◉</span><input type="range" min="0" max="3" value="0"></div><div class="map"><button data-world="morri">M</button><button data-world="witch">W</button><button data-world="xander">X</button><svg viewBox="0 0 100 100"><path d="M15 65 Q35 15 52 52 T86 30"/></svg></div><button class="drawer" data-hot="drawer">BORING HUMAN<br>DOCUMENTS</button><button class="red" id="red">DO NOT PUSH</button><div class="lamp"></div><div class="cables"></div></div><header><b>ARKMATX</b><span>THE WORKSHOP BETWEEN WORLDS</span></header><aside id="readout">Everything here probably does something.</aside><div id="modal" class="modal"><div><button id="close">×</button><p id="tag"></p><h1 id="title"></h1><p id="copy"></p><button id="go" hidden>TRAVEL</button></div></div></main>`;
const modal=document.querySelector('#modal'),title=document.querySelector('#title'),copy=document.querySelector('#copy'),tag=document.querySelector('#tag'),go=document.querySelector('#go'),readout=document.querySelector('#readout');
function show(t,c,k='WORKSHOP OBJECT'){tag.textContent=k;title.textContent=t;copy.textContent=c;go.hidden=true;modal.classList.add('show')}
document.querySelectorAll('[data-hot]').forEach(x=>x.onclick=()=>{const [t,c]=projects[x.dataset.hot];show(t,c)});
document.querySelectorAll('[data-world]').forEach(x=>x.onclick=()=>{const w=worlds[x.dataset.world];tag.textContent=w.status;title.textContent=w.label;copy.textContent=x.dataset.world==='morri'?'Door state: uncertain. Someone keeps moving the mushrooms.':x.dataset.world==='witch'?'Archive is growing. Marginalia detected in pages nobody remembers writing.':'Subject remains deceased. Continuity errors within acceptable limits.';go.hidden=false;go.onclick=()=>{document.body.className='travel '+x.dataset.world;setTimeout(()=>location.href=w.url,900)};modal.classList.add('show')});
document.querySelector('#close').onclick=()=>modal.classList.remove('show');
document.querySelector('#red').onclick=()=>{document.body.classList.toggle('alarm');readout.textContent=document.body.classList.contains('alarm')?'BAD IDEA. UNDOING BRUCE’S WORK…':'System restored. Mostly.'};
const tuner=document.querySelector('#radio input');tuner.oninput=()=>{const msgs=['static…','…rain on a cottage roof…','…pages turning where there is no wind…','…BRAAAINS? no. pizza…'];readout.textContent=msgs[+tuner.value]};
