import './style.css';
import './review.css';

const worlds={morri:{label:'MORRI HUT',url:'https://madmorrigan.com/morri/',status:'MYSTERY ENGINE // ONLINE'},witch:{label:'WITCHDIX',url:'https://witchdix.com/',status:'GRIMOIRE // LISTENING'},xander:{label:'XANDER ZOMBIE',url:'https://xanderzombie.com/',status:'NARRATIVE ENGINE // UNDEAD'}};
const key='realm-passport';
const incoming=(new URLSearchParams(location.search).get('rp')||'').split(',').filter(Boolean);
const passport=new Set([...(localStorage.getItem(key)||'').split(',').filter(Boolean),...incoming]);
const save=()=>localStorage.setItem(key,[...passport].join(','));
const travel=url=>{const u=new URL(url);u.searchParams.set('rp',[...passport].join(','));location.href=u.toString()};
save();

let activity=null;
let currentZone='workshop';
const logicState={a:false,b:false,c:false};

const worklog=()=>{if(!activity)return 'WORKLOG OFFLINE // activity.json unavailable';const lines=[activity.headline||'ARKMATX WEEKLY LOG',activity.summary||''];for(const p of activity.projects||[])lines.push(`${p.name} [${p.status}] — ${p.detail}`);lines.push('','RECENT GPT WORK:');for(const item of activity.weekly_log||[])lines.push(`> ${item}`);lines.push('',`LAST REFRESH: ${activity.updated_at||'unknown'}`);return lines.join('\n')};
const diagnostic=()=>['WORLD BUS DIAGNOSTIC',`MORRI: ${passport.has('morri-chess')?'ROOK HANDSHAKE':'UNRESOLVED'}`,`WITCHDIX: ${passport.has('witch-moon')?'MOON SIGIL':'LISTENING'}`,`XANDER: ${passport.has('xander-woods')?'INK PATH OPEN':'NARRATIVE STABLE'}`,`ARK: ${passport.has('ark-radio')?'RADIO LOCKED':'RADIO UNTUNED'}`].join('\n');

const workshop=`<section class="zone workshop-main active" data-zone="workshop"><div class="pipes"></div><div class="crt" data-hot="terminal"><b>ARKMATX</b><span>WORKSHOP OS<br>WORLD BUS: ACTIVE<br>FLAGS: ${passport.size}<br>_</span></div><div class="bench" data-hot="bench"><i></i><i></i><i></i><strong>TOOLS / PI / BAD IDEAS</strong></div><div class="bike" data-hot="bike">◯━╋━◯</div><div class="rack" data-hot="rack"><em></em><em></em><em></em><small>UBER // RACK 03</small></div><div class="radio" id="radio"><span>◉</span><input type="range" min="0" max="3" value="0"></div><div class="map"><button data-world="morri">M</button><button data-world="witch">W</button><button data-world="xander">X</button><svg viewBox="0 0 100 100"><path d="M15 65 Q35 15 52 52 T86 30"/></svg></div><button class="drawer" data-hot="drawer">BORING HUMAN<br>DOCUMENTS</button><button class="red" id="red">DO NOT PUSH</button><button class="worklog-machine" id="worklog"><b>GPT WORKLOG</b><small>LIVE WEEKLY FEED</small></button><button class="clipboard" id="clipboard">CURRENT BUILD STATUS<br>REAL PROJECTS ONLY<br>NO PORTFOLIO FLUFF</button><div class="glitch-note">IF THIS SITE DOCUMENTS THE WORK<br>AND THE WORK CHANGES THIS SITE,<br>WHICH ONE IS THE SOURCE?</div><div class="lamp"></div><div class="cables"></div><span class="easter-mark" id="egg">there is no basement</span><div class="navpad"><button data-go="servers">SERVER CLOSET →</button><button data-go="paradox">PARADOX TERMINAL →</button></div></section>`;

const servers=`<section class="zone server-room" data-zone="servers"><div class="zone-label">ARKMATX // SERVER CLOSET // PROBABLY UP TO CODE</div><div class="server-wall"><button class="server-bay" data-server="morri"><b>MORRI / MOSS NODE</b><i class="status-led"></i></button><button class="server-bay" data-server="witch"><b>WITCHDIX / PAPER NODE</b><i class="status-led"></i></button><button class="server-bay" data-server="xander"><b>XANDER / INK NODE</b><i class="status-led"></i></button><button class="server-bay" data-server="ark"><b>ARKMATX / LOOPBACK</b><i class="status-led"></i></button></div><div class="navpad"><button data-go="workshop">← WORKSHOP</button><button data-go="paradox">PARADOX TERMINAL →</button></div></section>`;

const paradox=`<section class="zone paradox-room" data-zone="paradox"><div class="zone-label">ARKMATX // PARADOX TERMINAL // ANSWERS MAY MODIFY QUESTIONS</div><div class="terminal-stack"><button class="logic-term" data-logic="a"><h3>TERMINAL A</h3><p>TERMINAL B IS LYING.\n\nCLICK ONLY IF THIS STATEMENT IS USEFUL.</p></button><button class="logic-term" data-logic="b"><h3>TERMINAL B</h3><p>EXACTLY ONE OF THESE TERMINALS TELLS THE TRUTH.\n\nTHIS TERMINAL IS NOT IT.</p></button><button class="logic-term" data-logic="c"><h3>TERMINAL C</h3><p>YOU ALREADY SOLVED THIS.\n\nTHE LOG SIMPLY HASN'T CAUGHT UP YET.</p></button></div><button class="logic-door" id="logicDoor" disabled>UNAUTHORIZED MAINTENANCE ACCESS</button><div class="navpad"><button data-go="workshop">← WORKSHOP</button><button data-go="servers">SERVER CLOSET</button></div></section>`;

document.querySelector('#app').innerHTML=`<main class="shop"><div class="room">${workshop}${servers}${paradox}</div><header><b>ARKMATX</b><span>THE WORKSHOP BETWEEN WORLDS</span></header><aside id="readout">Everything here probably does something.</aside><div id="modal" class="modal"><div><button id="close">×</button><p id="tag"></p><h1 id="title"></h1><p id="copy" style="white-space:pre-wrap"></p><button id="go" hidden>TRAVEL</button></div></div><div class="secret-console" id="secret"><div><h2>MAINTENANCE CHANNEL 0</h2><pre id="secretText"></pre><button id="secretClose">RETURN TO LESS QUESTIONABLE SYSTEMS</button></div></div></main>`;

const modal=document.querySelector('#modal'),title=document.querySelector('#title'),copy=document.querySelector('#copy'),tag=document.querySelector('#tag'),go=document.querySelector('#go'),readout=document.querySelector('#readout');
function show(t,c,k='WORKSHOP OBJECT'){tag.textContent=k;title.textContent=t;copy.textContent=c;go.hidden=true;modal.classList.add('show')}
function zone(name){currentZone=name;document.querySelectorAll('.zone').forEach(z=>z.classList.toggle('active',z.dataset.zone===name));readout.textContent=name==='workshop'?'Everything here probably does something.':name==='servers'?'Four machines. Three worlds. One machine claims it is the cable.':'Logic fault intentionally preserved.'}

document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>zone(b.dataset.go));
document.querySelector('#close').onclick=()=>modal.classList.remove('show');

fetch('./activity.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(j=>{activity=j;document.querySelector('#worklog small').textContent=(j.updated_at||'').slice(0,10)||'LIVE WEEKLY FEED'}).catch(()=>{readout.textContent='WORKLOG FEED OFFLINE. SOMETHING IS PROBABLY ON FIRE.'});
document.querySelector('#worklog').onclick=()=>show('WHAT BRUCE + GPT HAVE ACTUALLY BEEN DOING',worklog()+(activity?.easter_egg_seed?`\n\n// ${activity.easter_egg_seed}`:''),'LIVE LAB RECORD');
document.querySelector('#clipboard').onclick=()=>{const p=(activity?.projects||[]).map(x=>`${x.name.padEnd(14,'.')} ${x.status}`).join('\n');show('CURRENT SYSTEM STATE',p||'No feed loaded. The clipboard seems judgmental.','WEEKLY SNAPSHOT')};

const projectText={terminal:['BRAIN CONNECT',`AI orchestration / machines / experiments\n\n${diagnostic()}\n\nThis CRT is not pretending to be a project dashboard. It is one.`],bench:['WORKBENCH','Raspberry Pi · hardware · network experiments\n\nPhysical systems, remote-control experiments, security appliance ideas, and anything that required a cable before it required a website.'],bike:['WET BEARD','Quest engine escaped into the real world.\n\nRider game logic, quests, admin tools, deployments, and the evidence that a GPT project can eventually require an actual bicycle.'],rack:['ÜBERCORP','Space Pirates infrastructure and corporate interference.\n\nThe rack claims all services are mission critical. The rack is a liar.'],drawer:['BORING HUMAN DOCUMENTS','Résumé · work history · responsible-adult evidence\n\nFiled here to maintain plausible deniability.']};
document.querySelectorAll('[data-hot]').forEach(x=>x.onclick=()=>{const [t,c]=projectText[x.dataset.hot];show(t,c)});

document.querySelectorAll('[data-world]').forEach(x=>x.onclick=()=>{const w=worlds[x.dataset.world];tag.textContent=w.status;title.textContent=w.label;copy.textContent=x.dataset.world==='morri'?'Door state: uncertain. Someone keeps moving the mushrooms.':x.dataset.world==='witch'?'Archive is growing. Marginalia detected in pages nobody remembers writing.':'Subject remains deceased. Continuity errors within acceptable limits.';go.hidden=false;go.onclick=()=>{document.body.className='travel '+x.dataset.world;setTimeout(()=>travel(w.url),900)};modal.classList.add('show')});

document.querySelectorAll('[data-server]').forEach(b=>b.onclick=()=>{const s=b.dataset.server;const messages={morri:`MORRI NODE\nSTATUS: ${passport.has('morri-chess')?'ROOK HANDSHAKE ACCEPTED':'AWAITING CHESS EVENT'}\nTRANSPORT: moss / paper / door`,witch:`WITCHDIX NODE\nSTATUS: ${passport.has('witch-moon')?'MOON SIGIL ACTIVE':'GRIMOIRE LISTENING'}\nBACKEND: private notes + AI catalog`,xander:`XANDER NODE\nSTATUS: ${passport.has('xander-woods')?'IMPOSSIBLE PATH OPEN':'CANON STABLE'}\nENGINE: comic page / reel pipeline`,ark:`ARKMATX LOOPBACK\nSTATUS: observing itself observing itself\nWARNING: diagnostic result modifies diagnostic subject`};show('SERVER BAY '+s.toUpperCase(),messages[s],'LIVE MACHINE')});

const tuner=document.querySelector('#radio input');const sequence=[];const msgs=['static…','…rain on a cottage roof…','…pages turning where there is no wind…','…BRAAAINS? no. pizza…'];tuner.oninput=()=>{const v=+tuner.value;readout.textContent=msgs[v];if(v>0){sequence.push(v);if(sequence.length>3)sequence.shift();if(sequence.join('')==='123'){passport.add('ark-radio');save();readout.textContent='SIGNAL LOCK: MOSS / PAPER / INK. THREE WORLDS, ONE BUS.';setTimeout(()=>show('WORLD BUS LOCKED','The radio was not receiving three stations. It was triangulating one place from three directions.\n\nA fourth frequency has appeared below the dial.','UNAUTHORIZED DISCOVERY'),450)}}};

document.querySelector('#red').onclick=()=>{document.body.classList.toggle('alarm');passport.add('ark-red');save();readout.textContent=document.body.classList.contains('alarm')?'BAD IDEA. UNDOING BRUCE’S WORK… FLAG BROADCAST TO ALL REALMS.':'System restored. Mostly.'};

document.querySelectorAll('[data-logic]').forEach(b=>b.onclick=()=>{logicState[b.dataset.logic]=!logicState[b.dataset.logic];b.classList.toggle('solved',logicState[b.dataset.logic]);const valid=logicState.a&&!logicState.b&&logicState.c;document.querySelector('#logicDoor').disabled=!valid;readout.textContent=valid?'PARADOX ACCEPTED. ACCESS GRANTED FOR REASONS THE SYSTEM REFUSES TO EXPLAIN.':'The terminals disagree with your interpretation.'});
document.querySelector('#logicDoor').onclick=()=>{passport.add('ark-paradox');save();document.querySelector('#secretText').textContent=`YOU FOUND THE MAINTENANCE CHANNEL.\n\nRULE 1: If it looks like project information, it should be real.\nRULE 2: If it is fake, it should be part of a puzzle.\nRULE 3: A system that documents itself changes what it documents.\nRULE 4: There is no Rule 4.\n\nCURRENT FEED FLAGS: ${[...passport].join(', ')||'none'}\n\nNEXT MACHINE: waiting to be built.`;document.querySelector('#secret').classList.add('show')};
document.querySelector('#secretClose').onclick=()=>document.querySelector('#secret').classList.remove('show');
document.querySelector('#egg').onclick=()=>{readout.textContent='BASEMENT FLAG SET. THERE IS STILL NO BASEMENT.';passport.add('ark-basement');save()};
