<?php
session_start();
header('Cache-Control: no-store');
function jout($x,$code=200){http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function authed(){return !empty($_SESSION['xander_auth']);}
function need_auth(){if(!authed())jout(['ok'=>false,'error'=>'Studio locked.'],401);}
function ensure_dirs(){foreach(['data','data/drafts','data/uploads','generated'] as $d){$p=__DIR__.'/'.$d;if(!is_dir($p))@mkdir($p,0700,true);}foreach(['data','data/drafts','data/uploads'] as $d){$f=__DIR__.'/'.$d.'/.htaccess';if(!file_exists($f))@file_put_contents($f,"Require all denied\nDeny from all\n");}}
function episodes_path(){ensure_dirs();return __DIR__.'/data/episodes.jsonl';}
function all_episodes(){ $p=episodes_path(); if(!file_exists($p))return []; $out=[];$h=fopen($p,'r');while($h&&($l=fgets($h))!==false){$j=json_decode(trim($l),true);if(is_array($j))$out[]=$j;}if($h)fclose($h);usort($out,fn($a,$b)=>strcmp($b['published_at']??'',$a['published_at']??''));return $out;}
function public_episode($e){return ['id'=>$e['id'],'title'=>$e['title'],'issue'=>$e['issue'],'summary'=>$e['summary'],'panels'=>$e['panels'],'tags'=>$e['tags']??[],'art_url'=>$e['art_url']??'','published_at'=>$e['published_at']??''];}
function draft_path($id){return __DIR__.'/data/drafts/'.preg_replace('/[^a-z0-9_-]/i','',$id).'.json';}
function load_draft($id){$p=draft_path($id);if(!file_exists($p))return null;return json_decode(file_get_contents($p),true);}
function save_draft($d){ensure_dirs();file_put_contents(draft_path($d['id']),json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),LOCK_EX);}
function append_episode($e){$h=fopen(episodes_path(),'a');if(!$h)throw new Exception('Cannot open episode archive.');flock($h,LOCK_EX);fwrite($h,json_encode($e,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n");fflush($h);flock($h,LOCK_UN);fclose($h);}
function openai_json($prompt,$images=[]){$key=getenv('OPENAI_API_KEY');if(!$key)return null;$model=getenv('XANDER_WRITER_MODEL')?:'gpt-5.6-luna';$schema=['type'=>'object','properties'=>['title'=>['type'=>'string'],'summary'=>['type'=>'string'],'continuity_note'=>['type'=>'string'],'tags'=>['type'=>'array','items'=>['type'=>'string'],'maxItems'=>10],'canon_additions'=>['type'=>'array','items'=>['type'=>'string'],'maxItems'=>8],'panels'=>['type'=>'array','minItems'=>3,'maxItems'=>8,'items'=>['type'=>'object','properties'=>['caption'=>['type'=>'string'],'dialogue'=>['type'=>'string'],'visual'=>['type'=>'string'],'beat'=>['type'=>'string']],'required'=>['caption','dialogue','visual','beat'],'additionalProperties'=>false]]],'required'=>['title','summary','continuity_note','tags','canon_additions','panels'],'additionalProperties'=>false];$content=[['type'=>'input_text','text'=>$prompt]];foreach($images as $img){$content[]=['type'=>'input_image','image_url'=>'data:'.$img['mime'].';base64,'.base64_encode(file_get_contents($img['path']))];}$payload=['model'=>$model,'instructions'=>'Write an original Xander Zombie comic episode. Xander is a teenage boy first and zombie second. Keep the default tone dry, weird, warm, and mildly dark rather than graphic. Treat supplied memes/screenshots as story inspiration, not artwork to copy. Respect the supplied canon and recent episodes. Output only the requested schema.','input'=>[['role'=>'user','content'=>$content]],'text'=>['format'=>['type'=>'json_schema','name'=>'xander_episode','strict'=>true,'schema'=>$schema]]];$ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>75]);$r=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if(!$r||$code<200||$code>=300)return null;$j=json_decode($r,true);$txt='';foreach(($j['output']??[]) as $o)foreach(($o['content']??[]) as $c)if(($c['type']??'')==='output_text')$txt.=$c['text']??'';return json_decode($txt,true);
}
function generate_art($draft){$key=getenv('OPENAI_API_KEY');if(!$key)return null;$model=getenv('XANDER_IMAGE_MODEL')?:'gpt-image-2';$panels='';foreach($draft['plan']['panels'] as $i=>$p)$panels.="Panel ".($i+1).": {$p['visual']} Caption: {$p['caption']} Dialogue: {$p['dialogue']}\n";$prompt="Create one original portrait comic page for Xander Zombie. Teenage-zombie dark comedy, bold ink outlines, expressive faces, slightly grimy indie comic print texture, readable panel flow, mild/non-gory. Keep Xander visually consistent across panels. Do not imitate a named artist or reproduce supplied memes. Episode title: {$draft['plan']['title']}. Panels:\n{$panels}";$payload=['model'=>$model,'prompt'=>$prompt,'size'=>'1024x1536','quality'=>'medium','output_format'=>'png'];$ch=curl_init('https://api.openai.com/v1/images/generations');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>120]);$r=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if(!$r||$code<200||$code>=300)return null;$j=json_decode($r,true);$b64=$j['data'][0]['b64_json']??null;if(!$b64)return null;ensure_dirs();$name='generated/'.preg_replace('/[^a-z0-9_-]/i','',$draft['id']).'.png';file_put_contents(__DIR__.'/'.$name,base64_decode($b64));return $name;}
function body(){return json_decode(file_get_contents('php://input'),true)?:[];}
ensure_dirs();$action=$_POST['action']??(body()['action']??'');
if($action==='login'){$d=body();$pass=getenv('XANDER_STUDIO_PASSWORD');if(!$pass)jout(['ok'=>false,'error'=>'Studio password is not configured.'],503);if(!hash_equals($pass,(string)($d['password']??'')))jout(['ok'=>false,'error'=>'Nope. Wrong basement door.'],403);$_SESSION['xander_auth']=true;session_regenerate_id(true);jout(['ok'=>true]);}
if($action==='logout'){$_SESSION=[];session_destroy();jout(['ok'=>true]);}
if($action==='session')jout(['ok'=>true,'authenticated'=>authed()]);
if($action==='public_list')jout(['ok'=>true,'items'=>array_map('public_episode',array_slice(all_episodes(),0,50))]);
need_auth();
if($action==='intake'){$prompt=trim((string)($_POST['prompt']??''));$id=bin2hex(random_bytes(8));$uploads=[];if(!empty($_FILES['files']['name'])&&is_array($_FILES['files']['name'])){for($i=0;$i<count($_FILES['files']['name']);$i++){if($_FILES['files']['error'][$i]!==UPLOAD_ERR_OK)continue;$tmp=$_FILES['files']['tmp_name'][$i];$mime=mime_content_type($tmp)?:'application/octet-stream';if(!str_starts_with($mime,'image/'))continue;$ext=match($mime){'image/png'=>'png','image/webp'=>'webp',default=>'jpg'};$name="data/uploads/{$id}-{$i}.{$ext}";move_uploaded_file($tmp,__DIR__.'/'.$name);$uploads[]=['path'=>__DIR__.'/'.$name,'private_path'=>$name,'mime'=>$mime,'original'=>basename($_FILES['files']['name'][$i])];}}if($prompt===''&&!$uploads)jout(['ok'=>false,'error'=>'Give the studio a prompt, image, meme, or photo.'],422);$bible=json_decode(file_get_contents(__DIR__.'/story-bible.json'),true);$recent=array_map('public_episode',array_slice(all_episodes(),0,6));$context="STORY BIBLE:\n".json_encode($bible,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n\nRECENT APPROVED EPISODES:\n".json_encode($recent,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n\nXANDER'S NEW INPUT:\n{$prompt}";$plan=openai_json($context,$uploads);if(!$plan){$plan=['title'=>'Untitled Undead Problem','summary'=>$prompt?:'A new Xander Zombie episode.','continuity_note'=>'AI writer unavailable; manual edit required.','tags'=>['draft'],'canon_additions'=>[],'panels'=>[['caption'=>'Something happened.','dialogue'=>'This seems bad.','visual'=>'Xander reacts to the supplied idea.','beat'=>'setup'],['caption'=>'It gets more complicated.','dialogue'=>'Still probably grounded.','visual'=>'The teenage problem collides with the zombie problem.','beat'=>'complication'],['caption'=>'To be continued.','dialogue'=>'Can I at least get pizza?','visual'=>'Xander walks away from the consequences.','beat'=>'button']]];}$draft=['id'=>$id,'created_at'=>gmdate('c'),'prompt'=>$prompt,'uploads'=>array_map(fn($u)=>['private_path'=>$u['private_path'],'mime'=>$u['mime'],'original'=>$u['original']],$uploads),'plan'=>$plan,'art_url'=>'','status'=>'draft'];save_draft($draft);jout(['ok'=>true,'draft'=>$draft]);}
if($action==='save_plan'){$d=body();$dr=load_draft($d['id']??'');if(!$dr)jout(['ok'=>false,'error'=>'Draft not found.'],404);$plan=$d['plan']??null;if(!is_array($plan)||empty($plan['panels']))jout(['ok'=>false,'error'=>'Plan must contain panels.'],422);$dr['plan']=$plan;save_draft($dr);jout(['ok'=>true,'draft'=>$dr]);}
if($action==='render'){$d=body();$dr=load_draft($d['id']??'');if(!$dr)jout(['ok'=>false,'error'=>'Draft not found.'],404);$art=generate_art($dr);if(!$art)jout(['ok'=>false,'error'=>'Image generation is unavailable; the script is still saved.'],503);$dr['art_url']=$art;save_draft($dr);jout(['ok'=>true,'draft'=>$dr]);}
if($action==='publish'){$d=body();$dr=load_draft($d['id']??'');if(!$dr)jout(['ok'=>false,'error'=>'Draft not found.'],404);$issue=count(all_episodes())+1;$ep=['id'=>$dr['id'],'issue'=>$issue,'title'=>$dr['plan']['title'],'summary'=>$dr['plan']['summary'],'panels'=>$dr['plan']['panels'],'tags'=>$dr['plan']['tags']??[],'canon_additions'=>$dr['plan']['canon_additions']??[],'art_url'=>$dr['art_url']??'','source_prompt'=>$dr['prompt'],'published_at'=>gmdate('c')];append_episode($ep);$dr['status']='published';$dr['published_at']=$ep['published_at'];save_draft($dr);jout(['ok'=>true,'episode'=>public_episode($ep)]);}
if($action==='draft'){$d=body();$dr=load_draft($d['id']??'');if(!$dr)jout(['ok'=>false,'error'=>'Draft not found.'],404);jout(['ok'=>true,'draft'=>$dr]);}
jout(['ok'=>false,'error'=>'Unknown action.'],400);