import './style.css';
const key='realm-passport';const incoming=(new URLSearchParams(location.search).get('rp')||'').split(',').filter(Boolean);const passport=new Set([...(localStorage.getItem(key)||'').split(',').filter(Boolean),...incoming]);const save=()=>localStorage.setItem(key,[...passport].join(','));const jump=url=>{const u=new URL(url);u.searchParams.set('rp',[...passport].join(','));location.href=u.toString()};save();
const state={scene:'path',found:new Set(),board:['','♞','','','♚','','',''],chess:passport.has('morri-chess')};
const scenes={
 path:{title:'The Moss Path',note:passport.has('ark-red')?'The hut is watching the path. Somewhere far away, a red warning light pulses.':'The hut is watching the path.',bg:'./scenes/path.svg',hot:[['door','Enter the hut','610,225 1090,225 1110,785 590,785','parlor'],['mush','A pale mushroom','190,680 380,650 390,830 160,835','clue-mush']]},
 parlor:{title:'The Parlor',note:passport.has('ark-radio')?'Warm cedar. Rain on the glass. A faint radio tone is coming from beneath the floorboards.':'Warm cedar. Rain on the glass. Something clicks behind the walls.',bg:'./scenes/parlor.svg',hot:[['window','Moon window','850,95 1185,95 1195,520 835,520','window'],['cabinet','Curio cabinet','55,180 460,180 465,725 45,725','cabinet'],['board','Chess table','555,535 1035,520 1100,830 500,835','chess'],['floor','Loose floorboard','1250,650 1560,640 1590,890 1220,890',passport.has('ark-radio')?'underfloor':'clue-floor'],['door','Back outside','0,395 125,390 130,850 0,865','path']]},
 window:{title:'The Moon Window',note:passport.has('witch-moon')?'The eight leaves have changed. A knight-shaped shadow now sits among them.':'The glass is etched with eight tiny leaves.',bg:'./scenes/window.svg',hot:[['leaf','Etched leaves','490,165 1110,160 1170,690 430,695','clue-leaf'],['back','Step back','0,0 220,0 220,900 0,900','parlor']]},
 cabinet:{title:'The Cabinet',note:'A cabinet for objects that should probably have stayed in the forest.',bg:'./scenes/cabinet.svg',hot:[['scroll','Sealed scroll','335,150 770,150 780,405 320,410','clue-scroll'],['key','Brass key','905,490 1325,470 1350,770 880,790','clue-key'],['back','Step back','0,0 220,0 220,900 0,900','parlor']]},
 chess:{title:'The Chess Table',note:'Eight squares. A knight waits where no knight should.',bg:'./scenes/chess.svg',hot:[['back','Step back','0,0 220,0 220,900 0,900','parlor']]},
 secret:{title:'The Hidden Room',note:'Three paths leave the hut without using a door.',bg:'./scenes/secret.svg',hot:[['sigil','Wall sigil','670,70 930,70 955,330 645,330','clue-sigil'],['witch','A thorn-bound book','135,350 515,350 535,735 115,750','realm-witch'],['xander','A torn comic panel','590,340 1010,340 1025,750 575,755','realm-xander'],['ark','A humming brass terminal','1085,350 1460,350 1470,745 1070,750','realm-ark'],['back','Return','0,0 100,0 100,900 0,900','parlor']]},
 underfloor:{title:'Below the Floorboards',note:'This space should not fit beneath the hut. A copper wire disappears into the roots.',bg:'./scenes/underfloor.svg',hot:[['wire','Copper world-bus wire','380,510 1210,500 1225,690 360,700','clue-wire'],['back','Climb back up','0,0 220,0 220,900 0,900','parlor']]}
};
document.querySelector('#app').innerHTML=`<main class="game"><div id="scene" class="scene"><img id="sceneBg" class="scene-bg" alt=""><div class="mist-a"></div><div class="mist-b"></div></div><svg id="hotspots" viewBox="0 0 1600 900" preserveAspectRatio="xMidYMid slice"></svg><div class="grain"></div><header><span>MORRI</span><small id="place"></small></header><aside id="note"></aside><div id="inventory"><b>FOUND</b><span id="items">nothing yet</span></div><div id="toast"></div><button id="hint" aria-label="show hotspots">?</button></main>`;
const el=id=>document.getElementById(id),scene=el('scene'),sceneBg=el('sceneBg'),svg=el('hotspots'),note=el('note'),place=el('place'),toast=el('toast');
function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function add(item,label,msg){if(!state.found.has(item)){state.found.add(item);renderInv();say(msg)}else say('You already noticed that.')}
function renderInv(){el('items').textContent=[...state.found].map(x=>({mush:'pale mushroom',leaf:'8 leaves',scroll:'sealed scroll',key:'brass key',sigil:'rook sigil',floor:'loose board',wire:'copper wire'}[x])).join(' · ')||'nothing yet'}
function travel(url,text){const o=document.createElement('div');Object.assign(o.style,{position:'fixed',inset:'0',zIndex:'99',display:'grid',placeItems:'center',background:'#0b100cf2',color:'#d8ccb0',font:'italic 24px Georgia',letterSpacing:'.08em',textAlign:'center',transition:'opacity .5s'});o.textContent=text;document.body.append(o);setTimeout(()=>jump(url),900)}
function action(id,target){if(target==='realm-witch'){travel('https://madmorrigan.com/witchdix/?from=morri','The paper softens into bark. The air smells of rosemary…');return}if(target==='realm-xander'){travel('https://xanderzombie.com/?from=morri','The room flattens. Ink crawls around the edges…');return}if(target==='realm-ark'){travel('https://arkmatx.com/?from=morri','The lantern flickers like a bad CRT. Somewhere, a relay clicks…');return}if(target.startsWith('clue-')){const k=target.slice(5);const data={mush:['mush','pale mushroom','Its cap has a tiny carved ♞ beneath it.'],leaf:['leaf','8 leaves',passport.has('witch-moon')?'Eight leaves. The witch-page has changed one into a knight.':'Eight leaves. One is turned sideways like an L.'],scroll:['scroll','sealed scroll','The seal reads: “A knight enters where the forest bends.”'],key:['key','brass key','A tiny brass key. It has a rook cut into the bow.'],sigil:['sigil','rook sigil','The wall answers the key with a soft mechanical click.'],floor:['floor','loose board','One floorboard hums faintly, but it will not lift.'],wire:['wire','copper wire','The wire is warm. Scratched into it: ARK // 1-2-3.']}[k];add(...data);return}go(target)}
function go(name){state.scene=name;render()}
function render(){const s=scenes[state.scene];place.textContent=s.title;note.textContent=s.note;scene.dataset.scene=state.scene;sceneBg.src=s.bg;sceneBg.alt=s.title;sceneBg.style.animation='none';requestAnimationFrame(()=>sceneBg.style.animation='');svg.innerHTML=s.hot.map(h=>`<polygon tabindex="0" aria-label="${h[1]}" data-id="${h[0]}" data-target="${h[3]}" points="${h[2]}"/>`).join('');svg.querySelectorAll('polygon').forEach(p=>{p.onclick=()=>action(p.dataset.id,p.dataset.target);p.onkeydown=e=>{if(e.key==='Enter')p.click()}});document.querySelector('.boardWrap')?.remove();if(state.scene==='chess')renderBoard()}
function renderBoard(){const wrap=document.createElement('div');wrap.className='boardWrap';wrap.innerHTML=`<div id="board" class="board"></div><p class="boardHint">The knight remembers the leaves.</p>`;scene.append(wrap);const b=el('board');b.innerHTML=Array.from({length:8},(_,i)=>`<button class="sq ${i%2?'dark':''}" data-i="${i}">${state.board[i]}</button>`).join('');b.querySelectorAll('button').forEach(x=>x.onclick=()=>{const i=+x.dataset.i;if(state.board[i]==='♞'){state.board[i]='';state.board[(i+3)%8]='♞'}else if(!state.board[i]){const old=state.board.indexOf('♞');state.board[old]='';state.board[i]='♞'}renderBoard();checkChess()})}
function checkChess(){const knight=state.board.indexOf('♞');if(knight===4&&state.found.has('leaf')&&state.found.has('scroll')){state.chess=true;passport.add('morri-chess');save();say('A rook-shaped latch releases somewhere behind you. The other worlds felt that.');setTimeout(()=>go('secret'),900)}}
el('hint').onpointerdown=()=>document.body.classList.add('reveal-hotspots');el('hint').onpointerup=el('hint').onpointerleave=()=>document.body.classList.remove('reveal-hotspots');const from=new URLSearchParams(location.search).get('from');if(from){setTimeout(()=>say(from==='witchdix'?'You came back carrying the smell of rosemary.':from==='xander'?'A fleck of black ink follows you in.':'A faint electrical hum fades into the moss.'),400)}if(state.chess)setTimeout(()=>say('The hidden latch remembers you.'),700);render();