import './style.css';

const state={scene:'path',found:new Set(),board:['','♞','','','♚','','',''],chess:false};
const scenes={
path:{title:'The Moss Path',note:'The hut is watching the path.',hot:[['door','Enter the hut','42,28 61,29 64,79 39,79','parlor'],['mush','A pale mushroom','17,69 25,65 29,82 14,83','clue-mush']]},
parlor:{title:'The Parlor',note:'Warm cedar. Rain on the glass. Something clicks behind the walls.',hot:[['window','Moon window','67,14 94,12 95,65 70,63','window'],['cabinet','Curio cabinet','4,26 31,24 30,75 5,77','cabinet'],['board','Chess table','39,56 68,54 76,89 31,90','chess'],['door','Back outside','0,53 10,50 10,91 0,94','path']]},
window:{title:'The Moon Window',note:'The glass is etched with eight tiny leaves.',hot:[['leaf','Etched leaves','36,19 67,18 73,72 30,72','clue-leaf'],['back','Step back','0,0 17,0 17,100 0,100','parlor']]},
cabinet:{title:'The Cabinet',note:'A cabinet for objects that should probably have stayed in the forest.',hot:[['scroll','Sealed scroll','11,19 34,17 35,44 10,46','clue-scroll'],['key','Brass key','62,61 82,59 84,79 61,80','clue-key'],['back','Step back','0,0 15,0 15,100 0,100','parlor']]},
chess:{title:'The Chess Table',note:'Eight squares. A knight waits where no knight should.',hot:[['back','Step back','0,0 15,0 15,100 0,100','parlor']]},
secret:{title:'The Hidden Room',note:'Two paths leave the hut without using a door.',hot:[['sigil','Wall sigil','42,15 59,16 62,48 40,48','clue-sigil'],['witch','A thorn-bound book','18,49 41,48 41,82 17,84','realm-witch'],['xander','A torn comic panel','62,50 86,49 87,83 61,83','realm-xander'],['back','Return','0,0 12,0 12,100 0,100','parlor']]}
};

const sceneArt={
path:`<div class="sky"><i></i></div><div class="tree t1"></div><div class="tree t2"></div><div class="tree t3"></div><div class="hut"><div class="roof"></div><div class="moss"></div><div class="glow"></div><div class="doorShape"><b>M</b></div></div><div class="fog f1"></div><div class="fog f2"></div><div class="fungi">● ● · ●</div>`,
parlor:`<div class="beam"></div><div class="wall"></div><div class="cabinetShape"><i></i><i></i><i></i></div><div class="roundWindow"><div class="moon"></div><span>木</span></div><div class="fireGlow"></div><div class="chessTable"><span>♞</span></div><div class="rug"></div><div class="hangingHerbs">☘<br>☘</div>`,
window:`<div class="closeWindow"><div class="moon big"></div><div class="branches"></div><div class="leafRing">❧ ❧ ❧ ❧<br>❧ ❧ ❧ ❧</div></div><div class="windowSill">tea &nbsp; ◌ &nbsp; moss</div>`,
cabinet:`<div class="shelf s1"></div><div class="shelf s2"></div><div class="jar j1">✦</div><div class="jar j2">🍄</div><div class="scrollObj">巻</div><div class="keyObj">⌑</div><div class="mask">狐</div>`,
chess:`<div class="boardWrap"><div id="board" class="board"></div><p class="boardHint">The knight remembers the leaves.</p></div>`,
secret:`<div class="secretArch"></div><div class="sigilWall">♜<br><span>森</span></div><div style="position:absolute;left:18%;bottom:15%;width:22%;height:28%;background:#171911;border:2px solid #8d7650;box-shadow:0 0 35px #70905b44;display:grid;place-items:center;font:600 54px Georgia;color:#a7b38d;transform:rotate(-3deg)">☽<small style="display:block;font:10px sans-serif;letter-spacing:.14em">THORN BOOK</small></div><div style="position:absolute;right:14%;bottom:14%;width:24%;height:29%;background:#d7c9a7;color:#161616;border:7px solid #171717;box-shadow:9px 9px 0 #111;display:grid;place-items:center;font:900 46px Arial;transform:rotate(2deg)">Z!<small style="display:block;font:10px Arial;letter-spacing:.12em">TORN PANEL</small></div><div class="tinyLantern">✧</div>`
};

document.querySelector('#app').innerHTML=`<main class="game"><div id="scene" class="scene"></div><svg id="hotspots" viewBox="0 0 100 100" preserveAspectRatio="none"></svg><div class="grain"></div><header><span>MORRI</span><small id="place"></small></header><aside id="note"></aside><div id="inventory"><b>FOUND</b><span id="items">nothing yet</span></div><div id="toast"></div><button id="hint" aria-label="show hotspots">?</button></main>`;
const el=id=>document.getElementById(id), scene=el('scene'),svg=el('hotspots'),note=el('note'),place=el('place'),toast=el('toast');
function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function add(item,label,msg){if(!state.found.has(item)){state.found.add(item);renderInv();say(msg)}else say('You already noticed that.');}
function renderInv(){el('items').textContent=[...state.found].map(x=>({mush:'pale mushroom',leaf:'8 leaves',scroll:'sealed scroll',key:'brass key',sigil:'rook sigil'}[x])).join(' · ')||'nothing yet'}
function travel(url,text){const o=document.createElement('div');Object.assign(o.style,{position:'fixed',inset:'0',zIndex:'99',display:'grid',placeItems:'center',background:'#0b100cf2',color:'#d8ccb0',font:'italic 24px Georgia',letterSpacing:'.08em',textAlign:'center',transition:'opacity .5s'});o.textContent=text;document.body.append(o);setTimeout(()=>{location.href=url},900)}
function action(id,target){if(target==='realm-witch'){travel('https://witchdix.com/?from=morri','The paper softens into bark. The air smells of rosemary…');return}if(target==='realm-xander'){travel('https://xanderzombie.com/?from=morri','The room flattens. Ink crawls around the edges…');return}if(target.startsWith('clue-')){const k=target.slice(5);const data={mush:['mush','pale mushroom','Its cap has a tiny carved ♞ beneath it.'],leaf:['leaf','8 leaves','Eight leaves. One is turned sideways like an L.'],scroll:['scroll','sealed scroll','The seal reads: “A knight enters where the forest bends.”'],key:['key','brass key','A tiny brass key. It has a rook cut into the bow.'],sigil:['sigil','rook sigil','The wall answers the key with a soft mechanical click.']}[k];add(...data);return}go(target)}
function go(name){state.scene=name;render()}
function render(){const s=scenes[state.scene];place.textContent=s.title;note.textContent=s.note;scene.innerHTML=sceneArt[state.scene];scene.dataset.scene=state.scene;svg.innerHTML=s.hot.map(h=>`<polygon tabindex="0" aria-label="${h[1]}" data-id="${h[0]}" data-target="${h[3]}" points="${h[2]}"/>`).join('');svg.querySelectorAll('polygon').forEach(p=>{p.onclick=()=>action(p.dataset.id,p.dataset.target);p.onkeydown=e=>{if(e.key==='Enter')p.click()}});if(state.scene==='chess')renderBoard();}
function renderBoard(){const b=el('board');b.innerHTML=Array.from({length:8},(_,i)=>`<button class="sq ${i%2?'dark':''}" data-i="${i}">${state.board[i]}</button>`).join('');b.querySelectorAll('button').forEach(x=>x.onclick=()=>{const i=+x.dataset.i;if(state.board[i]==='♞'){state.board[i]='';state.board[(i+3)%8]='♞'}else if(!state.board[i]){const old=state.board.indexOf('♞');state.board[old]='';state.board[i]='♞'}renderBoard();checkChess()})}
function checkChess(){const knight=state.board.indexOf('♞');if(knight===4&&state.found.has('leaf')&&state.found.has('scroll')){state.chess=true;say('A rook-shaped latch releases somewhere behind you.');setTimeout(()=>go('secret'),900)}}
el('hint').onpointerdown=()=>document.body.classList.add('reveal-hotspots');el('hint').onpointerup=el('hint').onpointerleave=()=>document.body.classList.remove('reveal-hotspots');
const from=new URLSearchParams(location.search).get('from');if(from){setTimeout(()=>say(from==='witchdix'?'You came back carrying the smell of rosemary.':'A fleck of black ink follows you in.'),400)}render();
