<?php
session_start();
?><!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Heather's Writing Desk</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 50% 10%,#3e4934,#12170f 52%,#070a07);color:#2d281f;font-family:Georgia,serif}.desk{min-height:100vh;padding:4vh 4vw;display:grid;place-items:center}.book{width:min(1100px,96vw);min-height:82vh;background:linear-gradient(90deg,#b7a77e 0,#d9cba9 48.5%,#aa9972 50%,#d4c39e 52%);box-shadow:0 30px 90px #000;border-radius:12px 30px 30px 12px;position:relative;padding:5vh 5vw}.book:before{content:'';position:absolute;left:50%;top:0;bottom:0;width:3px;background:#6c5a3d55}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.top h1{margin:0;font-size:clamp(40px,6vw,76px);font-weight:500}.top small{letter-spacing:.18em}.quill{font-size:54px;transform:rotate(-18deg);filter:drop-shadow(4px 5px 2px #0003)}.spread{display:grid;grid-template-columns:1fr 1fr;gap:7vw;margin-top:4vh}.page h2{font-size:28px;font-weight:500;margin:0 0 12px}.page p{line-height:1.6;color:#524936}.ink{width:100%;min-height:310px;border:0;border-bottom:1px solid #766748;background:repeating-linear-gradient(transparent 0 31px,#76674822 32px);padding:8px 4px;color:#252018;font:20px/32px Georgia,serif;resize:vertical;outline:none}.field{width:100%;border:0;border-bottom:1px solid #766748;background:transparent;padding:9px 3px;font:17px Georgia;color:#2d281f;outline:none}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:18px}.btn{border:1px solid #5d5139;background:#302c20;color:#e1d6b9;padding:11px 17px;font:14px Georgia;cursor:pointer;box-shadow:3px 4px 0 #7d6c4990}.btn.secondary{background:#a99a75;color:#2b261d}.status{margin-top:14px;min-height:24px;font-style:italic;color:#63563d}.results{max-height:52vh;overflow:auto;padding-right:6px}.entry{padding:14px 0;border-bottom:1px solid #786a4b55}.entry h3{margin:0 0 5px;font-size:21px}.entry small{letter-spacing:.12em;color:#6d5d40}.entry p{margin:7px 0;line-height:1.45}.tags{font-size:12px;color:#665a42}.login{max-width:430px;margin:12vh auto}.login input{margin:10px 0}.hidden{display:none}@media(max-width:800px){.book{padding:4vh 7vw}.spread{grid-template-columns:1fr;gap:45px}.book:before{display:none}.results{max-height:none}}
</style></head><body><main class="desk"><section class="book"><div class="top"><div><small>PRIVATE WORKING COPY</small><h1>Heather's Writing Desk</h1><p>Write it messy. The catalog can sort it later.</p></div><div class="quill">🪶</div></div><div id="login" class="login"><h2>Open the private book</h2><input class="field" id="password" type="password" placeholder="password"><button class="btn" id="loginBtn">UNLOCK</button><div class="status" id="loginStatus"></div></div><div id="workspace" class="spread hidden"><section class="page"><h2>Fresh Ink</h2><input class="field" id="title" placeholder="Optional title"><textarea class="ink" id="note" placeholder="Write an idea, plant note, ritual, observation, recipe, dream, correspondence, strange thing found in the woods…"></textarea><input class="field" id="hint" placeholder="Optional hint: herb, ritual, moon, dream, recipe…"><div class="actions"><button class="btn" id="save">DRY THE INK & CATALOG</button><button class="btn secondary" id="clear">NEW PAGE</button></div><div class="status" id="status"></div></section><section class="page"><h2>Find in the Grimoire</h2><input class="field" id="search" placeholder="Search rosemary, protection, full moon, dream…"><div class="actions"><button class="btn secondary" id="searchBtn">SEARCH</button><button class="btn secondary" id="recentBtn">RECENT PAGES</button><button class="btn secondary" id="logout">CLOSE BOOK</button></div><div id="results" class="results"></div></section></div></section></main><script>
const $=s=>document.querySelector(s), api='api.php';
async function call(action,data={}){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||!j.ok)throw new Error(j.error||'Request failed');return j}
function showWorkspace(){ $('#login').classList.add('hidden');$('#workspace').classList.remove('hidden');loadRecent() }
async function check(){try{const r=await call('session');if(r.authenticated)showWorkspace()}catch{}}
$('#loginBtn').onclick=async()=>{try{await call('login',{password:$('#password').value});showWorkspace()}catch(e){$('#loginStatus').textContent=e.message}};
$('#save').onclick=async()=>{const raw=$('#note').value.trim();if(!raw)return;$('#status').textContent='The ink is drying. The index is thinking…';$('#save').disabled=true;try{const r=await call('add',{title:$('#title').value.trim(),raw,hint:$('#hint').value.trim()});$('#status').textContent=`Catalogued as “${r.entry.title}” · ${r.entry.category}`;$('#title').value='';$('#note').value='';$('#hint').value='';loadRecent()}catch(e){$('#status').textContent=e.message}finally{$('#save').disabled=false}};
$('#clear').onclick=()=>{$('#title').value='';$('#note').value='';$('#hint').value='';$('#status').textContent=''};
function render(items){$('#results').innerHTML=items.length?items.map(x=>`<article class="entry"><small>${esc(x.category||'uncatalogued')} · ${esc(x.created_at||'')}</small><h3>${esc(x.title||'Untitled page')}</h3><p>${esc(x.summary||x.raw||'')}</p><div class="tags">${(x.tags||[]).map(t=>'#'+esc(t)).join(' ')}</div></article>`).join(''):'<p>No matching pages.</p>'}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadRecent(){try{render((await call('list')).items)}catch(e){$('#results').textContent=e.message}}
$('#recentBtn').onclick=loadRecent;$('#searchBtn').onclick=async()=>{try{render((await call('search',{q:$('#search').value})).items)}catch(e){$('#results').textContent=e.message}};$('#search').onkeydown=e=>{if(e.key==='Enter')$('#searchBtn').click()};$('#logout').onclick=async()=>{await call('logout');location.reload()};check();
</script></body></html>